apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courier-service
  template:
    metadata:
      labels:
        app: courier-service
    spec:
      containers:
      - name: courier-service
        image: ghcr.io/IMAGE_OWNER/courier-service:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: courier-service
spec:
  selector:
    app: courier-service
  ports:
  - port: 3000
    targetPort: 3000
