apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: web-ui
        image: ghcr.io/IMAGE_OWNER/web-ui:IMAGE_TAG
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
spec:
  selector:
    app: web-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
