apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: user-service
        image: ghcr.io/IMAGE_OWNER/user-service:IMAGE_TAG
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_DB
          value: "users"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 3000
    targetPort: 3000
